### ISSUE TITLE
Android: Multiple definition of JNI_Onload

### ISSUE THREAD

**Issue by hrydgard** [erkkah/naett#13]
I'm already using a JNI_OnLoad in my app, so since naett defines one, I get a multiple definition error.

~~So what's needed is some way to pass your jni environment into naett, instead of having it try to grab it itself.~~ Scratch that, I see that naettPlatformInit can already do it. So I only need to get rid of the extra JNI_OnLoad somehow.

Can we have a define maybe? #ifdef USE_EXISTING_JNI_ONLOAD for example.

**Comment by erkkah** [comment]
Hi. That's a remainder from an early version, thanks for finding that.
You are supposed to pass the VM handle in the call to `naettInit`, the `JNI_OnLoad` is not needed.

**Comment by hrydgard** [comment]
Thanks for getting rid of it!

Might also be good to address #12, although I can't vouch for it as these JNI references confuse me sometimes as well..
