### ISSUE TITLE
local reference to 'buffer' in Android code is not deleted

### ISSUE THREAD

**Issue by GrahamAsher** [erkkah/naett#25]
The Java byte array 'buffer' is created here:

https://github.com/erkkah/naett/blob/10a9624456829e5f2b4c264e14760301125d12eb/naett.c#L1497

The function NewByteArray creates a local reference which is not deleted. The fix is to add this line after the 'finally' label, at line 1592 of naett.c:

``` (*env)->DeleteLocalRef(env,buffer);```

**Comment by erkkah** [comment]
Hi @GrahamAsher.
Is it actually leaking?
The `(*env)->PopLocalFrame(env, NULL);` should release all local references.
The unbounded ones (in loops) need to be explicitly released, but otherwise I think we're fine.

**Comment by GrahamAsher** [comment]
You're right. Sorry about that.
