### ISSUE TITLE
memory leaks: RequestOptions.method and InternalResponse.body.data not freed

### ISSUE THREAD

**Issue by GrahamAsher** [erkkah/naett#7]
I found copious memory leaks when using Naett in Windows. I was freeing up memory using naettFree for the naettReq object, and naettClose for the naettRes object,

The memory leaks can be fixed by adding `free(req->options.method);` to naettFree so that it becomes:

```
void naettFree(naettReq* request) {
    assert(request != NULL);

    InternalRequest* req = (InternalRequest*)request;
    naettPlatformFreeRequest(req);
    KVLink* node = req->options.headers;
    freeKVList(node);
    free((void*)req->url);
    free(req->options.method);
    free(request);
}
```

and adding `free(res->body.data);` to naettClose so that it becomes:

```
void naettClose(naettRes* response) {
    assert(response != NULL);

    InternalResponse* res = (InternalResponse*)response;
    res->request = NULL;
    naettPlatformCloseResponse(res);
    KVLink* node = res->headers;
    freeKVList(node);
    free(res->body.data);
    free(response);
}
```

**Comment by erkkah** [comment]
Hi @GrahamAsher! Thanks for all the reports. Since you have working code for all these issues, would you mind creating PRs for them?  I can update the ci/cd stuff and make sure the issues found are checked.

**Comment by GrahamAsher** [comment]
Hi Erik, I will try to find time to create PRs; but surely it is just as easy to apply the very simple patches that I have supplied? I'm not sure what you mean by ci/cd stuff.

**Comment by erkkah** [comment]
Well, I'm currently super-busy with other projects. If you already have
made the changes, I assumed you had them sitting in a fork.
Since my current setup is not Windows-based, it is more cumbersome for me
to actually add the code and verify it than just checking PRs.
The ci/cd stuff is the automatic build / verify step that is performed on
github actions.

**Comment by GrahamAsher** [comment]
And I'm super-super busy ;-) But I guess I'll find the time to make a fork.
